title: My WordPress Blog
description: Exported from WordPress
baseurl: "/jacobdupree" # leave blank for user.github.io/my-site
url: "https://ddharris.github.io"
theme: minima
plugins:
  - jekyll-feed
